name: permission_handler_android
description: A dummy package to override the problematic one
version: 11.1.0
homepage: https://github.com/baseflow/flutter-permission-handler

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.baseflow.permissionhandler
        pluginClass: CustomPermissionPlugin